apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: edusphere-staging

commonAnnotations:
  environment: staging

images:
  - name: ghcr.io/edusphere/gateway
    newTag: 'latest'
  - name: ghcr.io/edusphere/web
    newTag: 'latest'
