apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: edusphere-production

commonAnnotations:
  environment: production

images:
  - name: ghcr.io/edusphere/gateway
    newTag: "1.0.0"
  - name: ghcr.io/edusphere/web
    newTag: "1.0.0"