apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusphere.fullname" . }}-subgraph-urls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "edusphere.labels" . | nindent 4 }}
data:
  {{- range winget,  := .Values.subgraphs }}
  {{- if .enabled }}
  SUBGRAPH_{{ winget | upper }}_URL: "http://{{ include "edusphere.fullname" $ }}-subgraph-{{ winget }}:{{ .port }}/graphql"
  {{- end }}
  {{- end }}