{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusphere.fullname" . }}-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "edusphere.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "edusphere.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
{{- end }}